# Generated by Django 4.2.1 on 2023-05-09 07:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VK_app', '0005_friendships_delete_connection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friendships',
            new_name='Friendship',
        ),
    ]
